spring:
  application:
    name: springfox-swagger
server:
  port: 8080

# ===== \u81EA\u5B9A\u4E49swagger\u914D\u7F6E ===== #
myswagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: springfox swagger 3.0\u6574\u5408Demo
  try-host: http://localhost:${server.port}